// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx3s8SU5gYlFP2dYIElJu5LRHB4jvyduo',
    appId: '1:829645053195:web:9c7578601effdab126d60e',
    messagingSenderId: '829645053195',
    projectId: 'nas1-41450',
    authDomain: 'nas1-41450.firebaseapp.com',
    databaseURL: 'https://nas1-41450-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nas1-41450.appspot.com',
    measurementId: 'G-B25EC77LSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw9J28XSB1kO68k1qyzQbdv9T60GqmDwM',
    appId: '1:829645053195:android:278f59456b51d7a826d60e',
    messagingSenderId: '829645053195',
    projectId: 'nas1-41450',
    databaseURL: 'https://nas1-41450-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nas1-41450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYpy140m6MZQI0IN4ZOsgNwvDSXiNkAwA',
    appId: '1:829645053195:ios:571f5e2b6291561626d60e',
    messagingSenderId: '829645053195',
    projectId: 'nas1-41450',
    databaseURL: 'https://nas1-41450-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nas1-41450.appspot.com',
    iosClientId: '829645053195-ktnq6sd8pe5teohr2vgsnef78fir7iql.apps.googleusercontent.com',
    iosBundleId: 'com.example.nas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYpy140m6MZQI0IN4ZOsgNwvDSXiNkAwA',
    appId: '1:829645053195:ios:571f5e2b6291561626d60e',
    messagingSenderId: '829645053195',
    projectId: 'nas1-41450',
    databaseURL: 'https://nas1-41450-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nas1-41450.appspot.com',
    iosClientId: '829645053195-ktnq6sd8pe5teohr2vgsnef78fir7iql.apps.googleusercontent.com',
    iosBundleId: 'com.example.nas',
  );
}
